project:
  type: website

website:
  title: "DCD Analysis Pipeline"

format:
  html:
    toc: true
    embed-resources: true
    code-tools: false
    notebook-links: false
  pdf:
    toc: true
    number-sections: true
